# Generated by Django 5.0.6 on 2024-06-25 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="birthday",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_realname",
            field=models.CharField(default=19970911, max_length=150),
            preserve_default=False,
        ),
    ]
