# Generated by Django 5.0.6 on 2024-06-25 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="farm_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="FarmStatusLog",
            fields=[
                (
                    "farm_status_log_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("farm_status", models.IntegerField()),
                ("farm_created", models.DateTimeField(auto_now_add=True)),
                ("user_id", models.IntegerField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
