# Generated by Django 5.0.6 on 2024-07-02 02:39

import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0004_farmstatuslog_farm_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmstatuslog",
            name="farm_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=farm.models.generate_farm_image_filename,
            ),
        ),
    ]
