# Generated by Django 5.0.6 on 2024-07-02 05:10

import django.db.models.deletion
import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0005_alter_farmstatuslog_farm_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmstatuslog",
            name="farm_image",
        ),
        migrations.CreateModel(
            name="FarmImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=farm.models.generate_farm_image_filename,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
