# Generated by Django 5.0.6 on 2024-07-02 06:50

import django.db.models.deletion
import farm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0006_remove_farmstatuslog_farm_image_farmimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmimage",
            name="farm",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="farm.farm",
            ),
        ),
        migrations.AlterField(
            model_name="farmimage",
            name="farm_image",
            field=models.ImageField(
                blank=True, upload_to=farm.models.generate_farm_image_filename
            ),
        ),
    ]
