# Generated by Django 5.0.6 on 2024-07-09 02:04

import django.db.models.deletion
import farm.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0007_alter_farmimage_farm_alter_farmimage_farm_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="farm",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="FarmObjectDetectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_od_image",
                    models.ImageField(
                        upload_to=farm.utils.generate_farm_image_filename
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="od_image",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FarmPolygonDetectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "farm_pd_image",
                    models.ImageField(
                        upload_to=farm.utils.generate_farm_image_filename
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pd_image",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
