# Generated by Django 5.0.6 on 2024-07-10 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0008_farm_farm_geometry_alter_farm_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmobjectdetectionimage",
            name="farm_od_image",
        ),
        migrations.AlterField(
            model_name="farmpolygondetectionimage",
            name="farm",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="farm.farm"
            ),
        ),
    ]
