# Generated by Django 5.0.6 on 2024-07-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0009_remove_farmobjectdetectionimage_farm_od_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmstatuslog",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_log",
                to="farm.farm",
            ),
        ),
        migrations.CreateModel(
            name="FarmIllegalBuildingLog",
            fields=[
                (
                    "farm_illegal_building_log_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("farm_illegal_building_status", models.IntegerField()),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="illegal_log",
                        to="farm.farm",
                    ),
                ),
            ],
        ),
    ]
