# Generated by Django 5.0.6 on 2024-07-10 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("farm", "0010_alter_farmstatuslog_farm_farmillegalbuildinglog"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmillegalbuildinglog",
            name="farm_ib_log_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="farmillegalbuildinglog",
            name="farm",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="farm.farm"
            ),
        ),
        migrations.AlterField(
            model_name="farmstatuslog",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="farm.farm",
            ),
        ),
    ]
